services:
  frontend:
    build: .
    image: frontend-test-i:v1
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: frontend-test-c
